CREATE TABLE SQLANALYZER.CREDITCARD
(ID INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
USER_ID INTEGER NOT NULL,
CREDIT_CARD_NUMBER BIGINT,
CONSTRAINT fk_creditcard_user_master FOREIGN KEY(user_id) REFERENCES SQLANALYZER.USER_MASTER(ID) ON DELETE CASCADE,
PRIMARY KEY (ID));