CREATE TABLE SQLANALYZER.USER_MASTER
(ID INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
USERNAME VARCHAR(50),
PASSWORD VARCHAR(50),
EMAIL VARCHAR(100),
PRIMARY KEY (ID))